# Ready, Set, Numpy!

### Generate six random integers between 10 and 30. 


In [1]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[22 19 14 15 29 26]


### Create a 5x5 array with random values and find the minimum and maximum values. 



In [6]:
x = np.random.random((5,5))
print "\n Rnadom Array: \n ", x
xmin = x.min()
xmax = x.max()
print "\nMin: {0}, Max: {1}".format(xmin, xmax)


 Rnadom Array: 
  [[0.6008805  0.67177642 0.86637007 0.61146205 0.36595393]
 [0.36939456 0.18687407 0.68418552 0.89547201 0.62487128]
 [0.88047403 0.47675521 0.17936388 0.35976603 0.31767848]
 [0.74011052 0.03530595 0.90657674 0.53947307 0.40715968]
 [0.94344932 0.81131275 0.48869846 0.24334982 0.81659812]]

Min: 0.0353059511595, Max: 0.94344931673


### Generate a random array of 10 elements between 1 and 100 and sort it in reverse

In [17]:
a = np.random.randint(low=0, high=100, size=6)
a.sort()
print a[::-1]
# this also works
print -np.sort(-a)

[95 86 74 51 25  1]
[95 86 74 51 25  1]


### Generate a random 5X5 and calculate the mean of the 4th column

In [24]:
a = np.random.random((5,5))
print a
print a[:, 3].mean()

[[0.60677981 0.84576365 0.40865218 0.38832382 0.21611487]
 [0.28871196 0.55431082 0.40901912 0.42445747 0.90671971]
 [0.57072344 0.27772334 0.78443645 0.88110446 0.36548902]
 [0.53720125 0.33425161 0.56006989 0.26884423 0.58441361]
 [0.97671095 0.01267271 0.43546166 0.17487836 0.155558  ]]
0.4275216706700026


### Generate a random 5X5 and calculate the STD of the 2nd row

In [25]:
a = np.random.random((5,5))
print a
print a[2,:].std()

[[0.29134472 0.73785892 0.64018078 0.55741503 0.69372972]
 [0.03200123 0.43804778 0.93128634 0.3495726  0.26144235]
 [0.9351248  0.4964021  0.56689979 0.64090665 0.8327333 ]
 [0.94711485 0.57474609 0.00476071 0.6047949  0.3326981 ]
 [0.12273823 0.6266547  0.33864526 0.63755171 0.57893481]]
0.1645633844991145


### Create an array of natural numbers between 0 and 10 and Replace all odd numbers in arr with -1 

In [27]:
a = np.arange(10)
out = np.where(a % 2 == 1, -1, a)
print a
print out

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
